"""initial audit schema

Revision ID: dd4d9611c628
Revises:
Create Date: 2026-08-20 10:40:27.522629
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "dd4d9611c628"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "runs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("run_key", sa.String(), nullable=False),
        sa.Column("mode", sa.String(), nullable=False),
        sa.Column("scheduled_for", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("git_commit_sha", sa.String(), nullable=True),
        sa.Column("config_hash", sa.String(), nullable=False),
        sa.Column("agent_model", sa.String(), nullable=True),
        sa.Column("prompt_version", sa.String(), nullable=True),
        sa.Column("raw_artifact_path", sa.Text(), nullable=True),
        sa.Column("error_summary", sa.Text(), nullable=True),
        sa.CheckConstraint("mode = 'paper'", name=op.f("ck_runs_paper_mode_only")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_runs")),
        sa.UniqueConstraint("run_key", name=op.f("uq_runs_run_key")),
    )
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_runs_scheduled_for"), ["scheduled_for"], unique=False)
        batch_op.create_index(batch_op.f("ix_runs_status"), ["status"], unique=False)

    op.create_table(
        "strategies",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("markdown_path", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_strategies")),
        sa.UniqueConstraint("name", name=op.f("uq_strategies_name")),
    )
    with op.batch_alter_table("strategies", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_strategies_status"), ["status"], unique=False)

    op.create_table(
        "theses",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("invalidation_json", sa.Text(), nullable=False),
        sa.Column("markdown_path", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_theses")),
    )
    with op.batch_alter_table("theses", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_theses_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_theses_symbol"), ["symbol"], unique=False)
        batch_op.create_index("ix_theses_symbol_status", ["symbol", "status"], unique=False)

    op.create_table(
        "agent_invocations",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("purpose", sa.String(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("prompt_version", sa.String(), nullable=False),
        sa.Column("request_path", sa.Text(), nullable=False),
        sa.Column("response_path", sa.Text(), nullable=True),
        sa.Column("input_token_count", sa.Integer(), nullable=True),
        sa.Column("output_token_count", sa.Integer(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("error_summary", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
            name=op.f("fk_agent_invocations_run_id_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_invocations")),
    )
    with op.batch_alter_table("agent_invocations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_agent_invocations_run_id"), ["run_id"], unique=False)
        batch_op.create_index(
            "ix_agent_invocations_run_started", ["run_id", "started_at"], unique=False
        )

    op.create_table(
        "broker_orders",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("proposal_id", sa.String(), nullable=False),
        sa.Column("client_order_id", sa.String(), nullable=False),
        sa.Column("broker_order_id", sa.String(), nullable=True),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("side", sa.String(), nullable=False),
        sa.Column("order_type", sa.String(), nullable=False),
        sa.Column("qty", sa.String(), nullable=True),
        sa.Column("notional", sa.String(), nullable=True),
        sa.Column("limit_price", sa.String(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("raw_submission_path", sa.Text(), nullable=True),
        sa.Column("raw_json", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_broker_orders_run_id_runs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_broker_orders")),
        sa.UniqueConstraint("broker_order_id", name=op.f("uq_broker_orders_broker_order_id")),
        sa.UniqueConstraint("client_order_id", name=op.f("uq_broker_orders_client_order_id")),
    )
    with op.batch_alter_table("broker_orders", schema=None) as batch_op:
        batch_op.create_index("ix_broker_orders_proposal", ["proposal_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_broker_orders_run_id"), ["run_id"], unique=False)
        batch_op.create_index("ix_broker_orders_run_status", ["run_id", "status"], unique=False)
        batch_op.create_index(batch_op.f("ix_broker_orders_symbol"), ["symbol"], unique=False)

    op.create_table(
        "daily_reports",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("report_path", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_daily_reports_run_id_runs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_daily_reports")),
        sa.UniqueConstraint("run_id", "version", name=op.f("uq_daily_reports_run_id")),
    )
    with op.batch_alter_table("daily_reports", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_daily_reports_run_id"), ["run_id"], unique=False)

    op.create_table(
        "knowledge_changes",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("entity_type", sa.String(), nullable=False),
        sa.Column("entity_id", sa.String(), nullable=False),
        sa.Column("change_type", sa.String(), nullable=False),
        sa.Column("before_text", sa.Text(), nullable=False),
        sa.Column("after_text", sa.Text(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("evidence_ids_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
            name=op.f("fk_knowledge_changes_run_id_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_knowledge_changes")),
    )
    with op.batch_alter_table("knowledge_changes", schema=None) as batch_op:
        batch_op.create_index(
            "ix_knowledge_changes_entity_created", ["entity_id", "created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_knowledge_changes_entity_id"), ["entity_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_knowledge_changes_run_id"), ["run_id"], unique=False)

    op.create_table(
        "market_snapshots",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("quote_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("bid", sa.String(), nullable=True),
        sa.Column("ask", sa.String(), nullable=True),
        sa.Column("last", sa.String(), nullable=True),
        sa.Column("average_daily_dollar_volume", sa.String(), nullable=True),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("raw_json", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
            name=op.f("fk_market_snapshots_run_id_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_market_snapshots")),
        sa.UniqueConstraint(
            "run_id", "symbol", "quote_at", name=op.f("uq_market_snapshots_run_id")
        ),
    )
    with op.batch_alter_table("market_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_market_snapshots_content_hash"), ["content_hash"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_market_snapshots_run_id"), ["run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_market_snapshots_symbol"), ["symbol"], unique=False)
        batch_op.create_index(
            "ix_market_snapshots_symbol_quote", ["symbol", "quote_at"], unique=False
        )

    op.create_table(
        "performance_snapshots",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("run_id", sa.String(), nullable=True),
        sa.Column("period", sa.String(), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("equity", sa.String(), nullable=False),
        sa.Column("cash", sa.String(), nullable=True),
        sa.Column("pnl", sa.String(), nullable=True),
        sa.Column("return_pct", sa.String(), nullable=True),
        sa.Column("drawdown_pct", sa.String(), nullable=True),
        sa.Column("benchmark_symbol", sa.String(), nullable=True),
        sa.Column("benchmark_return_pct", sa.String(), nullable=True),
        sa.Column("raw_json", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
            name=op.f("fk_performance_snapshots_run_id_runs"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_performance_snapshots")),
        sa.UniqueConstraint("run_id", "period", name=op.f("uq_performance_snapshots_run_id")),
    )
    with op.batch_alter_table("performance_snapshots", schema=None) as batch_op:
        batch_op.create_index("ix_performance_snapshots_captured", ["captured_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_performance_snapshots_run_id"), ["run_id"], unique=False
        )

    op.create_table(
        "portfolio_snapshots",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("run_id", sa.String(), nullable=True),
        sa.Column("snapshot_type", sa.String(), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("equity", sa.String(), nullable=False),
        sa.Column("cash", sa.String(), nullable=False),
        sa.Column("buying_power", sa.String(), nullable=False),
        sa.Column("raw_json", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
            name=op.f("fk_portfolio_snapshots_run_id_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_portfolio_snapshots")),
    )
    with op.batch_alter_table("portfolio_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_portfolio_snapshots_captured_at"), ["captured_at"], unique=False
        )
        batch_op.create_index(
            "ix_portfolio_snapshots_run_captured", ["run_id", "captured_at"], unique=False
        )

    op.create_table(
        "research_items",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("source_type", sa.String(), nullable=False),
        sa.Column("source_name", sa.String(), nullable=False),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("author", sa.String(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("headline", sa.Text(), nullable=False),
        sa.Column("normalized_summary", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(), nullable=False),
        sa.Column("raw_content_path", sa.Text(), nullable=True),
        sa.Column("metadata_json", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_research_items_run_id_runs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_research_items")),
        sa.UniqueConstraint("content_hash", name=op.f("uq_research_items_content_hash")),
    )
    with op.batch_alter_table("research_items", schema=None) as batch_op:
        batch_op.create_index("ix_research_items_published", ["published_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_research_items_run_id"), ["run_id"], unique=False)
        batch_op.create_index(
            "ix_research_items_run_retrieved", ["run_id", "retrieved_at"], unique=False
        )

    op.create_table(
        "risk_decisions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("proposal_id", sa.String(), nullable=False),
        sa.Column("approved", sa.Boolean(), nullable=False),
        sa.Column("reason_codes_json", sa.Text(), nullable=False),
        sa.Column("normalized_order_json", sa.Text(), nullable=True),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("policy_hash", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_risk_decisions_run_id_runs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_risk_decisions")),
        sa.UniqueConstraint("run_id", "proposal_id", name=op.f("uq_risk_decisions_run_id")),
    )
    with op.batch_alter_table("risk_decisions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_risk_decisions_proposal_id"), ["proposal_id"], unique=False
        )
        batch_op.create_index(
            "ix_risk_decisions_run_created", ["run_id", "created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_risk_decisions_run_id"), ["run_id"], unique=False)

    op.create_table(
        "run_events",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("stage", sa.String(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("metadata_json", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_run_events_run_id_runs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run_events")),
    )
    with op.batch_alter_table("run_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_run_events_run_id"), ["run_id"], unique=False)
        batch_op.create_index("ix_run_events_run_occurred", ["run_id", "occurred_at"], unique=False)

    op.create_table(
        "thesis_strategy_links",
        sa.Column("thesis_id", sa.String(), nullable=False),
        sa.Column("strategy_id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["strategy_id"],
            ["strategies.id"],
            name=op.f("fk_thesis_strategy_links_strategy_id_strategies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["thesis_id"],
            ["theses.id"],
            name=op.f("fk_thesis_strategy_links_thesis_id_theses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("thesis_id", "strategy_id", name=op.f("pk_thesis_strategy_links")),
    )
    op.create_table(
        "broker_order_events",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("broker_order_id", sa.String(), nullable=False),
        sa.Column("event_key", sa.String(), nullable=False),
        sa.Column("broker_event_id", sa.String(), nullable=True),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw_event_path", sa.Text(), nullable=True),
        sa.Column("raw_json", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["broker_order_id"],
            ["broker_orders.id"],
            name=op.f("fk_broker_order_events_broker_order_id_broker_orders"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_broker_order_events")),
        sa.UniqueConstraint("broker_event_id", name=op.f("uq_broker_order_events_broker_event_id")),
        sa.UniqueConstraint("event_key", name=op.f("uq_broker_order_events_event_key")),
    )
    with op.batch_alter_table("broker_order_events", schema=None) as batch_op:
        batch_op.create_index(
            "ix_broker_order_events_order_occurred",
            ["broker_order_id", "occurred_at"],
            unique=False,
        )

    op.create_table(
        "fills",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("broker_order_id", sa.String(), nullable=False),
        sa.Column("broker_activity_id", sa.String(), nullable=False),
        sa.Column("qty", sa.String(), nullable=False),
        sa.Column("price", sa.String(), nullable=False),
        sa.Column("side", sa.String(), nullable=False),
        sa.Column("transaction_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("commission", sa.String(), nullable=True),
        sa.Column("raw_activity_path", sa.Text(), nullable=True),
        sa.Column("raw_json", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["broker_order_id"],
            ["broker_orders.id"],
            name=op.f("fk_fills_broker_order_id_broker_orders"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fills")),
        sa.UniqueConstraint("broker_activity_id", name=op.f("uq_fills_broker_activity_id")),
    )
    with op.batch_alter_table("fills", schema=None) as batch_op:
        batch_op.create_index(
            "ix_fills_order_transaction", ["broker_order_id", "transaction_time"], unique=False
        )

    op.create_table(
        "position_snapshots",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("portfolio_snapshot_id", sa.String(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("qty", sa.String(), nullable=False),
        sa.Column("market_value", sa.String(), nullable=False),
        sa.Column("current_price", sa.String(), nullable=False),
        sa.Column("average_entry_price", sa.String(), nullable=True),
        sa.Column("unrealized_pl", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["portfolio_snapshot_id"],
            ["portfolio_snapshots.id"],
            name=op.f("fk_position_snapshots_portfolio_snapshot_id_portfolio_snapshots"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_position_snapshots")),
        sa.UniqueConstraint(
            "portfolio_snapshot_id",
            "symbol",
            name=op.f("uq_position_snapshots_portfolio_snapshot_id"),
        ),
    )
    with op.batch_alter_table("position_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_position_snapshots_portfolio_snapshot_id"),
            ["portfolio_snapshot_id"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_position_snapshots_symbol"), ["symbol"], unique=False)
        batch_op.create_index(
            "ix_position_snapshots_symbol_snapshot",
            ["symbol", "portfolio_snapshot_id"],
            unique=False,
        )

    op.create_table(
        "thesis_evidence",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("thesis_id", sa.String(), nullable=False),
        sa.Column("research_id", sa.String(), nullable=False),
        sa.Column("relationship", sa.String(), nullable=False),
        sa.Column("agent_explanation", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["research_id"],
            ["research_items.id"],
            name=op.f("fk_thesis_evidence_research_id_research_items"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["thesis_id"],
            ["theses.id"],
            name=op.f("fk_thesis_evidence_thesis_id_theses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_thesis_evidence")),
        sa.UniqueConstraint("thesis_id", "research_id", name=op.f("uq_thesis_evidence_thesis_id")),
    )
    with op.batch_alter_table("thesis_evidence", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_thesis_evidence_research_id"), ["research_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_thesis_evidence_thesis_id"), ["thesis_id"], unique=False
        )

    op.create_table(
        "trade_proposals",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("agent_invocation_id", sa.String(), nullable=True),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("requested_notional", sa.String(), nullable=True),
        sa.Column("target_position_pct", sa.String(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("thesis_id", sa.String(), nullable=True),
        sa.Column("raw_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["agent_invocation_id"],
            ["agent_invocations.id"],
            name=op.f("fk_trade_proposals_agent_invocation_id_agent_invocations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_trade_proposals_run_id_runs"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["thesis_id"],
            ["theses.id"],
            name=op.f("fk_trade_proposals_thesis_id_theses"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trade_proposals")),
    )
    with op.batch_alter_table("trade_proposals", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_trade_proposals_agent_invocation_id"),
            ["agent_invocation_id"],
            unique=False,
        )
        batch_op.create_index(
            "ix_trade_proposals_run_created", ["run_id", "created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_trade_proposals_run_id"), ["run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_trade_proposals_symbol"), ["symbol"], unique=False)
        batch_op.create_index(
            "ix_trade_proposals_symbol_created", ["symbol", "created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_trade_proposals_thesis_id"), ["thesis_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("trade_proposals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_trade_proposals_thesis_id"))
        batch_op.drop_index("ix_trade_proposals_symbol_created")
        batch_op.drop_index(batch_op.f("ix_trade_proposals_symbol"))
        batch_op.drop_index(batch_op.f("ix_trade_proposals_run_id"))
        batch_op.drop_index("ix_trade_proposals_run_created")
        batch_op.drop_index(batch_op.f("ix_trade_proposals_agent_invocation_id"))

    op.drop_table("trade_proposals")
    with op.batch_alter_table("thesis_evidence", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_thesis_evidence_thesis_id"))
        batch_op.drop_index(batch_op.f("ix_thesis_evidence_research_id"))

    op.drop_table("thesis_evidence")
    with op.batch_alter_table("position_snapshots", schema=None) as batch_op:
        batch_op.drop_index("ix_position_snapshots_symbol_snapshot")
        batch_op.drop_index(batch_op.f("ix_position_snapshots_symbol"))
        batch_op.drop_index(batch_op.f("ix_position_snapshots_portfolio_snapshot_id"))

    op.drop_table("position_snapshots")
    with op.batch_alter_table("fills", schema=None) as batch_op:
        batch_op.drop_index("ix_fills_order_transaction")

    op.drop_table("fills")
    with op.batch_alter_table("broker_order_events", schema=None) as batch_op:
        batch_op.drop_index("ix_broker_order_events_order_occurred")

    op.drop_table("broker_order_events")
    op.drop_table("thesis_strategy_links")
    with op.batch_alter_table("run_events", schema=None) as batch_op:
        batch_op.drop_index("ix_run_events_run_occurred")
        batch_op.drop_index(batch_op.f("ix_run_events_run_id"))

    op.drop_table("run_events")
    with op.batch_alter_table("risk_decisions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_risk_decisions_run_id"))
        batch_op.drop_index("ix_risk_decisions_run_created")
        batch_op.drop_index(batch_op.f("ix_risk_decisions_proposal_id"))

    op.drop_table("risk_decisions")
    with op.batch_alter_table("research_items", schema=None) as batch_op:
        batch_op.drop_index("ix_research_items_run_retrieved")
        batch_op.drop_index(batch_op.f("ix_research_items_run_id"))
        batch_op.drop_index("ix_research_items_published")

    op.drop_table("research_items")
    with op.batch_alter_table("portfolio_snapshots", schema=None) as batch_op:
        batch_op.drop_index("ix_portfolio_snapshots_run_captured")
        batch_op.drop_index(batch_op.f("ix_portfolio_snapshots_captured_at"))

    op.drop_table("portfolio_snapshots")
    with op.batch_alter_table("performance_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_performance_snapshots_run_id"))
        batch_op.drop_index("ix_performance_snapshots_captured")

    op.drop_table("performance_snapshots")
    with op.batch_alter_table("market_snapshots", schema=None) as batch_op:
        batch_op.drop_index("ix_market_snapshots_symbol_quote")
        batch_op.drop_index(batch_op.f("ix_market_snapshots_symbol"))
        batch_op.drop_index(batch_op.f("ix_market_snapshots_run_id"))
        batch_op.drop_index(batch_op.f("ix_market_snapshots_content_hash"))

    op.drop_table("market_snapshots")
    with op.batch_alter_table("knowledge_changes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_knowledge_changes_run_id"))
        batch_op.drop_index(batch_op.f("ix_knowledge_changes_entity_id"))
        batch_op.drop_index("ix_knowledge_changes_entity_created")

    op.drop_table("knowledge_changes")
    with op.batch_alter_table("daily_reports", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_daily_reports_run_id"))

    op.drop_table("daily_reports")
    with op.batch_alter_table("broker_orders", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_broker_orders_symbol"))
        batch_op.drop_index("ix_broker_orders_run_status")
        batch_op.drop_index(batch_op.f("ix_broker_orders_run_id"))
        batch_op.drop_index("ix_broker_orders_proposal")

    op.drop_table("broker_orders")
    with op.batch_alter_table("agent_invocations", schema=None) as batch_op:
        batch_op.drop_index("ix_agent_invocations_run_started")
        batch_op.drop_index(batch_op.f("ix_agent_invocations_run_id"))

    op.drop_table("agent_invocations")
    with op.batch_alter_table("theses", schema=None) as batch_op:
        batch_op.drop_index("ix_theses_symbol_status")
        batch_op.drop_index(batch_op.f("ix_theses_symbol"))
        batch_op.drop_index(batch_op.f("ix_theses_status"))

    op.drop_table("theses")
    with op.batch_alter_table("strategies", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_strategies_status"))

    op.drop_table("strategies")
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_runs_status"))
        batch_op.drop_index(batch_op.f("ix_runs_scheduled_for"))

    op.drop_table("runs")
    # ### end Alembic commands ###
